<template>
  <div>
    <v-tabs
      align-with-title
      next-icon="mdi-arrow-right-bold-box-outline"
      prev-icon="mdi-arrow-left-bold-box-outline"
      show-arrows
    >
      <v-tab v-for="(item, index) in tabs" :key="index">{{ item }}</v-tab>

      <v-tab-item v-for="(item, index) in tabs" :key="index">
        <v-row justify="start" align="start" align-content="start">
          <v-col v-for="(icon, index) in icons[item]" :key="index">
            <v-tooltip top>
              <template v-slot:activator="{ on, attrs }">
                <v-btn
                  icon
                  color="primary"
                  dark
                  v-bind="attrs"
                  v-on="on"
                  @click="copyIcon(icon.icon, $event)"
                >
                  <v-icon color="primary">{{ icon.icon }}</v-icon>
                </v-btn>
              </template>
              <span>{{ icon.icon }}</span>
            </v-tooltip>
          </v-col>
        </v-row>
      </v-tab-item>
    </v-tabs>
  </div>
</template>
<script>
import clipboard from "@/utils/clipboard.js";
export default {
  data: () => ({
    tabs: [
      "New",
      "Web Application Icons",
      "Accessibility Icons",
      "Hand Icons",
      "Transportation Icons",
      "Gender Icons",
      "File Type Icons",
      "Spinner Icons",
      "Form Control Icons",
      "Payment Icons",
      "Chart Icons",
      "Currency Icons",
      "Text Editor Icons",
      "Directional Icons",
      "Video Player Icons",
      "Brand Icons",
      "Medical Icons",
    ],
    icons: {
      "New": [
        { icon: "fa-address-book" },
        { icon: "fa-address-book-o" },
        { icon: "fa-address-card" },
        { icon: "fa-address-card-o" },
        { icon: "fa-bandcamp" },
        { icon: "fa-bath" },
        { icon: "fa-bathtub" },
        { icon: "fa-drivers-license" },
        { icon: "fa-drivers-license-o" },
        { icon: "fa-eercast" },
        { icon: "fa-envelope-open" },
        { icon: "fa-envelope-open-o" },
        { icon: "fa-etsy" },
        { icon: "fa-free-code-camp" },
        { icon: "fa-grav" },
        { icon: "fa-handshake-o" },
        { icon: "fa-id-badge" },
        { icon: "fa-id-card" },
        { icon: "fa-id-card-o" },
        { icon: "fa-imdb" },
        { icon: "fa-linode" },
        { icon: "fa-meetup" },
        { icon: "fa-microchip" },
        { icon: "fa-podcast" },
        { icon: "fa-quora" },
        { icon: "fa-ravelry" },
        { icon: "fa-s15" },
        { icon: "fa-shower" },
        { icon: "fa-snowflake-o" },
        { icon: "fa-superpowers" },
        { icon: "fa-telegram" },
        { icon: "fa-thermometer" },
        { icon: "fa-thermometer-0" },
        { icon: "fa-thermometer-1" },
        { icon: "fa-thermometer-2" },
        { icon: "fa-thermometer-3" },
        { icon: "fa-thermometer-4" },
        { icon: "fa-thermometer-empty" },
        { icon: "fa-thermometer-full" },
        { icon: "fa-thermometer-half" },
        { icon: "fa-thermometer-quarter" },
        { icon: "fa-thermometer-three-quarters" },
        { icon: "fa-times-rectangle" },
        { icon: "fa-times-rectangle-o" },
        { icon: "fa-user-circle" },
        { icon: "fa-user-circle-o" },
        { icon: "fa-user-o" },
        { icon: "fa-vcard" },
        { icon: "fa-vcard-o" },
        { icon: "fa-window-close" },
        { icon: "fa-window-close-o" },
        { icon: "fa-window-maximize" },
        { icon: "fa-window-minimize" },
        { icon: "fa-window-restore" },
        { icon: "fa-wpexplorer" },
      ],
      "Web Application Icons": [
        { icon: "fa-address-book" },
        { icon: "fa-address-book-o" },
        { icon: "fa-address-card" },
        { icon: "fa-address-card-o" },
        { icon: "fa-adjust" },
        { icon: "fa-american-sign-language-interpreting" },
        { icon: "fa-anchor" },
        { icon: "fa-archive" },
        { icon: "fa-area-chart" },
        { icon: "fa-arrows" },
        { icon: "fa-arrows-h" },
        { icon: "fa-arrows-v" },
        { icon: "fa-asl-interpreting" },
        { icon: "fa-assistive-listening-systems" },
        { icon: "fa-asterisk" },
        { icon: "fa-at" },
        { icon: "fa-audio-description" },
        { icon: "fa-automobile" },
        { icon: "fa-balance-scale" },
        { icon: "fa-ban" },
        { icon: "fa-bank" },
        { icon: "fa-bar-chart" },
        { icon: "fa-bar-chart-o" },
        { icon: "fa-barcode" },
        { icon: "fa-bars" },
        { icon: "fa-bath" },
        { icon: "fa-bathtub" },
        { icon: "fa-battery" },
        { icon: "fa-battery-0" },
        { icon: "fa-battery-1" },
        { icon: "fa-battery-2" },
        { icon: "fa-battery-3" },
        { icon: "fa-battery-4" },
        { icon: "fa-battery-empty" },
        { icon: "fa-battery-full" },
        { icon: "fa-battery-half" },
        { icon: "fa-battery-quarter" },
        { icon: "fa-battery-three-quarters" },
        { icon: "fa-bed" },
        { icon: "fa-beer" },
        { icon: "fa-bell" },
        { icon: "fa-bell-o" },
        { icon: "fa-bell-slash" },
        { icon: "fa-bell-slash-o" },
        { icon: "fa-bicycle" },
        { icon: "fa-binoculars" },
        { icon: "fa-birthday-cake" },
        { icon: "fa-blind" },
        { icon: "fa-bluetooth" },
        { icon: "fa-bluetooth-b" },
        { icon: "fa-bolt" },
        { icon: "fa-bomb" },
        { icon: "fa-book" },
        { icon: "fa-bookmark" },
        { icon: "fa-bookmark-o" },
        { icon: "fa-braille" },
        { icon: "fa-briefcase" },
        { icon: "fa-bug" },
        { icon: "fa-building" },
        { icon: "fa-building-o" },
        { icon: "fa-bullhorn" },
        { icon: "fa-bullseye" },
        { icon: "fa-bus" },
        { icon: "fa-cab" },
        { icon: "fa-calculator" },
        { icon: "fa-calendar" },
        { icon: "fa-calendar-check-o" },
        { icon: "fa-calendar-minus-o" },
        { icon: "fa-calendar-o" },
        { icon: "fa-calendar-plus-o" },
        { icon: "fa-calendar-times-o" },
        { icon: "fa-camera" },
        { icon: "fa-camera-retro" },
        { icon: "fa-car" },
        { icon: "fa-caret-square-o-down" },
        { icon: "fa-caret-square-o-left" },
        { icon: "fa-caret-square-o-right" },
        { icon: "fa-caret-square-o-up" },
        { icon: "fa-cart-arrow-down" },
        { icon: "fa-cart-plus" },
        { icon: "fa-cc" },
        { icon: "fa-certificate" },
        { icon: "fa-check" },
        { icon: "fa-check-circle" },
        { icon: "fa-check-circle-o" },
        { icon: "fa-check-square" },
        { icon: "fa-check-square-o" },
        { icon: "fa-child" },
        { icon: "fa-circle" },
        { icon: "fa-circle-o" },
        { icon: "fa-circle-o-notch" },
        { icon: "fa-circle-thin" },
        { icon: "fa-clock-o" },
        { icon: "fa-clone" },
        { icon: "fa-close" },
        { icon: "fa-cloud" },
        { icon: "fa-cloud-download" },
        { icon: "fa-cloud-upload" },
        { icon: "fa-code" },
        { icon: "fa-code-fork" },
        { icon: "fa-coffee" },
        { icon: "fa-cog" },
        { icon: "fa-cogs" },
        { icon: "fa-comment" },
        { icon: "fa-comment-o" },
        { icon: "fa-commenting" },
        { icon: "fa-commenting-o" },
        { icon: "fa-comments" },
        { icon: "fa-comments-o" },
        { icon: "fa-compass" },
        { icon: "fa-copyright" },
        { icon: "fa-creative-commons" },
        { icon: "fa-credit-card" },
        { icon: "fa-credit-card-alt" },
        { icon: "fa-crop" },
        { icon: "fa-crosshairs" },
        { icon: "fa-cube" },
        { icon: "fa-cubes" },
        { icon: "fa-cutlery" },
        { icon: "fa-dashboard" },
        { icon: "fa-database" },
        { icon: "fa-deaf" },
        { icon: "fa-deafness" },
        { icon: "fa-desktop" },
        { icon: "fa-diamond" },
        { icon: "fa-dot-circle-o" },
        { icon: "fa-download" },
        { icon: "fa-drivers-license" },
        { icon: "fa-drivers-license-o" },
        { icon: "fa-edit" },
        { icon: "fa-ellipsis-h" },
        { icon: "fa-ellipsis-v" },
        { icon: "fa-envelope" },
        { icon: "fa-envelope-o" },
        { icon: "fa-envelope-open" },
        { icon: "fa-envelope-open-o" },
        { icon: "fa-envelope-square" },
        { icon: "fa-eraser" },
        { icon: "fa-exchange" },
        { icon: "fa-exclamation" },
        { icon: "fa-exclamation-circle" },
        { icon: "fa-exclamation-triangle" },
        { icon: "fa-external-link" },
        { icon: "fa-external-link-square" },
        { icon: "fa-eye" },
        { icon: "fa-eye-slash" },
        { icon: "fa-eyedropper" },
        { icon: "fa-fax" },
        { icon: "fa-feed" },
        { icon: "fa-female" },
        { icon: "fa-fighter-jet" },
        { icon: "fa-file-archive-o" },
        { icon: "fa-file-audio-o" },
        { icon: "fa-file-code-o" },
        { icon: "fa-file-excel-o" },
        { icon: "fa-file-image-o" },
        { icon: "fa-file-movie-o" },
        { icon: "fa-file-pdf-o" },
        { icon: "fa-file-photo-o" },
        { icon: "fa-file-picture-o" },
        { icon: "fa-file-powerpoint-o" },
        { icon: "fa-file-sound-o" },
        { icon: "fa-file-video-o" },
        { icon: "fa-file-word-o" },
        { icon: "fa-file-zip-o" },
        { icon: "fa-film" },
        { icon: "fa-filter" },
        { icon: "fa-fire" },
        { icon: "fa-fire-extinguisher" },
        { icon: "fa-flag" },
        { icon: "fa-flag-checkered" },
        { icon: "fa-flag-o" },
        { icon: "fa-flash" },
        { icon: "fa-flask" },
        { icon: "fa-folder" },
        { icon: "fa-folder-o" },
        { icon: "fa-folder-open" },
        { icon: "fa-folder-open-o" },
        { icon: "fa-frown-o" },
        { icon: "fa-futbol-o" },
        { icon: "fa-gamepad" },
        { icon: "fa-gavel" },
        { icon: "fa-gear" },
        { icon: "fa-gears" },
        { icon: "fa-gift" },
        { icon: "fa-glass" },
        { icon: "fa-globe" },
        { icon: "fa-graduation-cap" },
        { icon: "fa-group" },
        { icon: "fa-hand-grab-o" },
        { icon: "fa-hand-lizard-o" },
        { icon: "fa-hand-paper-o" },
        { icon: "fa-hand-peace-o" },
        { icon: "fa-hand-pointer-o" },
        { icon: "fa-hand-rock-o" },
        { icon: "fa-hand-scissors-o" },
        { icon: "fa-hand-spock-o" },
        { icon: "fa-hand-stop-o" },
        { icon: "fa-handshake-o" },
        { icon: "fa-hard-of-hearing" },
        { icon: "fa-hashtag" },
        { icon: "fa-hdd-o" },
        { icon: "fa-headphones" },
        { icon: "fa-heart" },
        { icon: "fa-heart-o" },
        { icon: "fa-heartbeat" },
        { icon: "fa-history" },
        { icon: "fa-home" },
        { icon: "fa-hotel" },
        { icon: "fa-hourglass" },
        { icon: "fa-hourglass-1" },
        { icon: "fa-hourglass-2" },
        { icon: "fa-hourglass-3" },
        { icon: "fa-hourglass-end" },
        { icon: "fa-hourglass-half" },
        { icon: "fa-hourglass-o" },
        { icon: "fa-hourglass-start" },
        { icon: "fa-i-cursor" },
        { icon: "fa-id-badge" },
        { icon: "fa-id-card" },
        { icon: "fa-id-card-o" },
        { icon: "fa-image" },
        { icon: "fa-inbox" },
        { icon: "fa-industry" },
        { icon: "fa-info" },
        { icon: "fa-info-circle" },
        { icon: "fa-institution" },
        { icon: "fa-key" },
        { icon: "fa-keyboard-o" },
        { icon: "fa-language" },
        { icon: "fa-laptop" },
        { icon: "fa-leaf" },
        { icon: "fa-legal" },
        { icon: "fa-lemon-o" },
        { icon: "fa-level-down" },
        { icon: "fa-level-up" },
        { icon: "fa-life-bouy" },
        { icon: "fa-life-buoy" },
        { icon: "fa-life-ring" },
        { icon: "fa-life-saver" },
        { icon: "fa-lightbulb-o" },
        { icon: "fa-line-chart" },
        { icon: "fa-location-arrow" },
        { icon: "fa-lock" },
        { icon: "fa-low-vision" },
        { icon: "fa-magic" },
        { icon: "fa-magnet" },
        { icon: "fa-mail-forward" },
        { icon: "fa-mail-reply" },
        { icon: "fa-mail-reply-all" },
        { icon: "fa-male" },
        { icon: "fa-map" },
        { icon: "fa-map-marker" },
        { icon: "fa-map-o" },
        { icon: "fa-map-pin" },
        { icon: "fa-map-signs" },
        { icon: "fa-meh-o" },
        { icon: "fa-microchip" },
        { icon: "fa-microphone" },
        { icon: "fa-microphone-slash" },
        { icon: "fa-minus" },
        { icon: "fa-minus-circle" },
        { icon: "fa-minus-square" },
        { icon: "fa-minus-square-o" },
        { icon: "fa-mobile" },
        { icon: "fa-mobile-phone" },
        { icon: "fa-money" },
        { icon: "fa-moon-o" },
        { icon: "fa-mortar-board" },
        { icon: "fa-motorcycle" },
        { icon: "fa-mouse-pointer" },
        { icon: "fa-music" },
        { icon: "fa-navicon" },
        { icon: "fa-newspaper-o" },
        { icon: "fa-object-group" },
        { icon: "fa-object-ungroup" },
        { icon: "fa-paint-brush" },
        { icon: "fa-paper-plane" },
        { icon: "fa-paper-plane-o" },
        { icon: "fa-paw" },
        { icon: "fa-pencil" },
        { icon: "fa-pencil-square" },
        { icon: "fa-pencil-square-o" },
        { icon: "fa-percent" },
        { icon: "fa-phone" },
        { icon: "fa-phone-square" },
        { icon: "fa-photo" },
        { icon: "fa-picture-o" },
        { icon: "fa-pie-chart" },
        { icon: "fa-plane" },
        { icon: "fa-plug" },
        { icon: "fa-plus" },
        { icon: "fa-plus-circle" },
        { icon: "fa-plus-square" },
        { icon: "fa-plus-square-o" },
        { icon: "fa-podcast" },
        { icon: "fa-power-off" },
        { icon: "fa-print" },
        { icon: "fa-puzzle-piece" },
        { icon: "fa-qrcode" },
        { icon: "fa-question" },
        { icon: "fa-question-circle" },
        { icon: "fa-question-circle-o" },
        { icon: "fa-quote-left" },
        { icon: "fa-quote-right" },
        { icon: "fa-random" },
        { icon: "fa-recycle" },
        { icon: "fa-refresh" },
        { icon: "fa-registered" },
        { icon: "fa-remove" },
        { icon: "fa-reorder" },
        { icon: "fa-reply" },
        { icon: "fa-reply-all" },
        { icon: "fa-retweet" },
        { icon: "fa-road" },
        { icon: "fa-rocket" },
        { icon: "fa-rss" },
        { icon: "fa-rss-square" },
        { icon: "fa-s15" },
        { icon: "fa-search" },
        { icon: "fa-search-minus" },
        { icon: "fa-search-plus" },
        { icon: "fa-send" },
        { icon: "fa-send-o" },
        { icon: "fa-server" },
        { icon: "fa-share" },
        { icon: "fa-share-alt" },
        { icon: "fa-share-alt-square" },
        { icon: "fa-share-square" },
        { icon: "fa-share-square-o" },
        { icon: "fa-shield" },
        { icon: "fa-ship" },
        { icon: "fa-shopping-bag" },
        { icon: "fa-shopping-basket" },
        { icon: "fa-shopping-cart" },
        { icon: "fa-shower" },
        { icon: "fa-sign-in" },
        { icon: "fa-sign-language" },
        { icon: "fa-sign-out" },
        { icon: "fa-signal" },
        { icon: "fa-signing" },
        { icon: "fa-sitemap" },
        { icon: "fa-sliders" },
        { icon: "fa-smile-o" },
        { icon: "fa-snowflake-o" },
        { icon: "fa-soccer-ball-o" },
        { icon: "fa-sort" },
        { icon: "fa-sort-alpha-asc" },
        { icon: "fa-sort-alpha-desc" },
        { icon: "fa-sort-amount-asc" },
        { icon: "fa-sort-amount-desc" },
        { icon: "fa-sort-asc" },
        { icon: "fa-sort-desc" },
        { icon: "fa-sort-down" },
        { icon: "fa-sort-numeric-asc" },
        { icon: "fa-sort-numeric-desc" },
        { icon: "fa-sort-up" },
        { icon: "fa-space-shuttle" },
        { icon: "fa-spinner" },
        { icon: "fa-spoon" },
        { icon: "fa-square" },
        { icon: "fa-square-o" },
        { icon: "fa-star" },
        { icon: "fa-star-half" },
        { icon: "fa-star-half-empty" },
        { icon: "fa-star-half-full" },
        { icon: "fa-star-half-o" },
        { icon: "fa-star-o" },
        { icon: "fa-sticky-note" },
        { icon: "fa-sticky-note-o" },
        { icon: "fa-street-view" },
        { icon: "fa-suitcase" },
        { icon: "fa-sun-o" },
        { icon: "fa-support" },
        { icon: "fa-tablet" },
        { icon: "fa-tachometer" },
        { icon: "fa-tag" },
        { icon: "fa-tags" },
        { icon: "fa-tasks" },
        { icon: "fa-taxi" },
        { icon: "fa-television" },
        { icon: "fa-terminal" },
        { icon: "fa-thermometer" },
        { icon: "fa-thermometer-0" },
        { icon: "fa-thermometer-1" },
        { icon: "fa-thermometer-2" },
        { icon: "fa-thermometer-3" },
        { icon: "fa-thermometer-4" },
        { icon: "fa-thermometer-empty" },
        { icon: "fa-thermometer-full" },
        { icon: "fa-thermometer-half" },
        { icon: "fa-thermometer-quarter" },
        { icon: "fa-thermometer-three-quarters" },
        { icon: "fa-thumb-tack" },
        { icon: "fa-thumbs-down" },
        { icon: "fa-thumbs-o-down" },
        { icon: "fa-thumbs-o-up" },
        { icon: "fa-thumbs-up" },
        { icon: "fa-ticket" },
        { icon: "fa-times" },
        { icon: "fa-times-circle" },
        { icon: "fa-times-circle-o" },
        { icon: "fa-times-rectangle" },
        { icon: "fa-times-rectangle-o" },
        { icon: "fa-tint" },
        { icon: "fa-toggle-down" },
        { icon: "fa-toggle-left" },
        { icon: "fa-toggle-off" },
        { icon: "fa-toggle-on" },
        { icon: "fa-toggle-right" },
        { icon: "fa-toggle-up" },
        { icon: "fa-trademark" },
        { icon: "fa-trash" },
        { icon: "fa-trash-o" },
        { icon: "fa-tree" },
        { icon: "fa-trophy" },
        { icon: "fa-truck" },
        { icon: "fa-tty" },
        { icon: "fa-tv" },
        { icon: "fa-umbrella" },
        { icon: "fa-universal-access" },
        { icon: "fa-university" },
        { icon: "fa-unlock" },
        { icon: "fa-unlock-alt" },
        { icon: "fa-unsorted" },
        { icon: "fa-upload" },
        { icon: "fa-user" },
        { icon: "fa-user-circle" },
        { icon: "fa-user-circle-o" },
        { icon: "fa-user-o" },
        { icon: "fa-user-plus" },
        { icon: "fa-user-secret" },
        { icon: "fa-user-times" },
        { icon: "fa-users" },
        { icon: "fa-vcard" },
        { icon: "fa-vcard-o" },
        { icon: "fa-video-camera" },
        { icon: "fa-volume-control-phone" },
        { icon: "fa-volume-down" },
        { icon: "fa-volume-off" },
        { icon: "fa-volume-up" },
        { icon: "fa-warning" },
        { icon: "fa-wheelchair" },
        { icon: "fa-wheelchair-alt" },
        { icon: "fa-wifi" },
        { icon: "fa-window-close" },
        { icon: "fa-window-close-o" },
        { icon: "fa-window-maximize" },
        { icon: "fa-window-minimize" },
        { icon: "fa-window-restore" },
        { icon: "fa-wrench" },
      ],
      "Accessibility Icons": [
        { icon: "fa-american-sign-language-interpreting" },
        { icon: "fa-asl-interpreting" },
        { icon: "fa-assistive-listening-systems" },
        { icon: "fa-audio-description" },
        { icon: "fa-blind" },
        { icon: "fa-braille" },
        { icon: "fa-cc" },
        { icon: "fa-deaf" },
        { icon: "fa-deafness" },
        { icon: "fa-hard-of-hearing" },
        { icon: "fa-low-vision" },
        { icon: "fa-question-circle-o" },
        { icon: "fa-sign-language" },
        { icon: "fa-signing" },
        { icon: "fa-tty" },
        { icon: "fa-universal-access" },
        { icon: "fa-volume-control-phone" },
        { icon: "fa-wheelchair" },
        { icon: "fa-wheelchair-alt" },
      ],
      "Hand Icons": [
        { icon: "fa-hand-grab-o" },
        { icon: "fa-hand-lizard-o" },
        { icon: "fa-hand-o-down" },
        { icon: "fa-hand-o-left" },
        { icon: "fa-hand-o-right" },
        { icon: "fa-hand-o-up" },
        { icon: "fa-hand-paper-o" },
        { icon: "fa-hand-peace-o" },
        { icon: "fa-hand-pointer-o" },
        { icon: "fa-hand-rock-o" },
        { icon: "fa-hand-scissors-o" },
        { icon: "fa-hand-spock-o" },
        { icon: "fa-hand-stop-o" },
        { icon: "fa-thumbs-down" },
        { icon: "fa-thumbs-o-down" },
        { icon: "fa-thumbs-o-up" },
        { icon: "fa-thumbs-up" },
      ],
      "Transportation Icons": [
        { icon: "fa-ambulance" },
        { icon: "fa-automobile" },
        { icon: "fa-bicycle" },
        { icon: "fa-bus" },
        { icon: "fa-cab" },
        { icon: "fa-car" },
        { icon: "fa-fighter-jet" },
        { icon: "fa-motorcycle" },
        { icon: "fa-plane" },
        { icon: "fa-rocket" },
        { icon: "fa-ship" },
        { icon: "fa-space-shuttle" },
        { icon: "fa-subway" },
        { icon: "fa-taxi" },
        { icon: "fa-train" },
        { icon: "fa-truck" },
        { icon: "fa-wheelchair" },
        { icon: "fa-wheelchair-alt" },
      ],
      "Gender Icons": [
        { icon: "fa-genderless" },
        { icon: "fa-intersex" },
        { icon: "fa-mars" },
        { icon: "fa-mars-double" },
        { icon: "fa-mars-stroke" },
        { icon: "fa-mars-stroke-h" },
        { icon: "fa-mars-stroke-v" },
        { icon: "fa-mercury" },
        { icon: "fa-neuter" },
        { icon: "fa-transgender" },
        { icon: "fa-transgender-alt" },
        { icon: "fa-venus" },
        { icon: "fa-venus-double" },
        { icon: "fa-venus-mars" },
      ],
      "File Type Icons": [
        { icon: "fa-file" },
        { icon: "fa-file-archive-o" },
        { icon: "fa-file-audio-o" },
        { icon: "fa-file-code-o" },
        { icon: "fa-file-excel-o" },
        { icon: "fa-file-image-o" },
        { icon: "fa-file-movie-o" },
        { icon: "fa-file-o" },
        { icon: "fa-file-pdf-o" },
        { icon: "fa-file-photo-o" },
        { icon: "fa-file-picture-o" },
        { icon: "fa-file-powerpoint-o" },
        { icon: "fa-file-sound-o" },
        { icon: "fa-file-text" },
        { icon: "fa-file-text-o" },
        { icon: "fa-file-video-o" },
        { icon: "fa-file-word-o" },
        { icon: "fa-file-zip-o" },
      ],
      "Spinner Icons": [
        { icon: "fa-circle-o-notch" },
        { icon: "fa-cog" },
        { icon: "fa-gear" },
        { icon: "fa-refresh" },
        { icon: "fa-spinner" },
      ],
      "Form Control Icons": [
        { icon: "fa-check-square" },
        { icon: "fa-check-square-o" },
        { icon: "fa-circle" },
        { icon: "fa-circle-o" },
        { icon: "fa-dot-circle-o" },
        { icon: "fa-minus-square" },
        { icon: "fa-minus-square-o" },
        { icon: "fa-plus-square" },
        { icon: "fa-plus-square-o" },
        { icon: "fa-square" },
        { icon: "fa-square-o" },
      ],
      "Payment Icons": [
        { icon: "fa-cc-amex" },
        { icon: "fa-cc-diners-club" },
        { icon: "fa-cc-discover" },
        { icon: "fa-cc-jcb" },
        { icon: "fa-cc-mastercard" },
        { icon: "fa-cc-paypal" },
        { icon: "fa-cc-stripe" },
        { icon: "fa-cc-visa" },
        { icon: "fa-credit-card" },
        { icon: "fa-credit-card-alt" },
        { icon: "fa-google-wallet" },
        { icon: "fa-paypal" },
      ],
      "Chart Icons": [
        { icon: "fa-area-chart" },
        { icon: "fa-bar-chart" },
        { icon: "fa-bar-chart-o" },
        { icon: "fa-line-chart" },
        { icon: "fa-pie-chart" },
      ],
      "Currency Icons": [
        { icon: "fa-bitcoin" },
        { icon: "fa-btc" },
        { icon: "fa-cny" },
        { icon: "fa-dollar" },
        { icon: "fa-eur" },
        { icon: "fa-euro" },
        { icon: "fa-gbp" },
        { icon: "fa-gg" },
        { icon: "fa-gg-circle" },
        { icon: "fa-ils" },
        { icon: "fa-inr" },
        { icon: "fa-jpy" },
        { icon: "fa-krw" },
        { icon: "fa-money" },
        { icon: "fa-rmb" },
        { icon: "fa-rouble" },
        { icon: "fa-rub" },
        { icon: "fa-ruble" },
        { icon: "fa-rupee" },
        { icon: "fa-shekel" },
        { icon: "fa-sheqel" },
        { icon: "fa-try" },
        { icon: "fa-turkish-lira" },
        { icon: "fa-usd" },
        { icon: "fa-won" },
        { icon: "fa-yen" },
      ],
      "Text Editor Icons": [
        { icon: "fa-align-center" },
        { icon: "fa-align-justify" },
        { icon: "fa-align-left" },
        { icon: "fa-align-right" },
        { icon: "fa-bold" },
        { icon: "fa-chain" },
        { icon: "fa-chain-broken" },
        { icon: "fa-clipboard" },
        { icon: "fa-columns" },
        { icon: "fa-copy" },
        { icon: "fa-cut" },
        { icon: "fa-dedent" },
        { icon: "fa-eraser" },
        { icon: "fa-file" },
        { icon: "fa-file-o" },
        { icon: "fa-file-text" },
        { icon: "fa-file-text-o" },
        { icon: "fa-files-o" },
        { icon: "fa-floppy-o" },
        { icon: "fa-font" },
        { icon: "fa-header" },
        { icon: "fa-indent" },
        { icon: "fa-italic" },
        { icon: "fa-link" },
        { icon: "fa-list" },
        { icon: "fa-list-alt" },
        { icon: "fa-list-ol" },
        { icon: "fa-list-ul" },
        { icon: "fa-outdent" },
        { icon: "fa-paperclip" },
        { icon: "fa-paragraph" },
        { icon: "fa-paste" },
        { icon: "fa-repeat" },
        { icon: "fa-rotate-left" },
        { icon: "fa-rotate-right" },
        { icon: "fa-save" },
        { icon: "fa-scissors" },
        { icon: "fa-strikethrough" },
        { icon: "fa-subscript" },
        { icon: "fa-superscript" },
        { icon: "fa-table" },
        { icon: "fa-text-height" },
        { icon: "fa-text-width" },
        { icon: "fa-th" },
        { icon: "fa-th-large" },
        { icon: "fa-th-list" },
        { icon: "fa-underline" },
        { icon: "fa-undo" },
        { icon: "fa-unlink" },
      ],
      "Directional Icons": [
        { icon: "fa-angle-double-down" },
        { icon: "fa-angle-double-left" },
        { icon: "fa-angle-double-right" },
        { icon: "fa-angle-double-up" },
        { icon: "fa-angle-down" },
        { icon: "fa-angle-left" },
        { icon: "fa-angle-right" },
        { icon: "fa-angle-up" },
        { icon: "fa-arrow-circle-down" },
        { icon: "fa-arrow-circle-left" },
        { icon: "fa-arrow-circle-o-down" },
        { icon: "fa-arrow-circle-o-left" },
        { icon: "fa-arrow-circle-o-right" },
        { icon: "fa-arrow-circle-o-up" },
        { icon: "fa-arrow-circle-right" },
        { icon: "fa-arrow-circle-up" },
        { icon: "fa-arrow-down" },
        { icon: "fa-arrow-left" },
        { icon: "fa-arrow-right" },
        { icon: "fa-arrow-up" },
        { icon: "fa-arrows" },
        { icon: "fa-arrows-alt" },
        { icon: "fa-arrows-h" },
        { icon: "fa-arrows-v" },
        { icon: "fa-caret-down" },
        { icon: "fa-caret-left" },
        { icon: "fa-caret-right" },
        { icon: "fa-caret-square-o-down" },
        { icon: "fa-caret-square-o-left" },
        { icon: "fa-caret-square-o-right" },
        { icon: "fa-caret-square-o-up" },
        { icon: "fa-caret-up" },
        { icon: "fa-chevron-circle-down" },
        { icon: "fa-chevron-circle-left" },
        { icon: "fa-chevron-circle-right" },
        { icon: "fa-chevron-circle-up" },
        { icon: "fa-chevron-down" },
        { icon: "fa-chevron-left" },
        { icon: "fa-chevron-right" },
        { icon: "fa-chevron-up" },
        { icon: "fa-exchange" },
        { icon: "fa-hand-o-down" },
        { icon: "fa-hand-o-left" },
        { icon: "fa-hand-o-right" },
        { icon: "fa-hand-o-up" },
        { icon: "fa-long-arrow-down" },
        { icon: "fa-long-arrow-left" },
        { icon: "fa-long-arrow-right" },
        { icon: "fa-long-arrow-up" },
        { icon: "fa-toggle-down" },
        { icon: "fa-toggle-left" },
        { icon: "fa-toggle-right" },
        { icon: "fa-toggle-up" },
      ],
      "Video Player Icons": [
        { icon: "fa-arrows-alt" },
        { icon: "fa-backward" },
        { icon: "fa-compress" },
        { icon: "fa-eject" },
        { icon: "fa-expand" },
        { icon: "fa-fast-backward" },
        { icon: "fa-fast-forward" },
        { icon: "fa-forward" },
        { icon: "fa-pause" },
        { icon: "fa-pause-circle" },
        { icon: "fa-pause-circle-o" },
        { icon: "fa-play" },
        { icon: "fa-play-circle" },
        { icon: "fa-play-circle-o" },
        { icon: "fa-random" },
        { icon: "fa-step-backward" },
        { icon: "fa-step-forward" },
        { icon: "fa-stop" },
        { icon: "fa-stop-circle" },
        { icon: "fa-stop-circle-o" },
        { icon: "fa-youtube-play" },
      ],
      "Brand Icons": [
        { icon: "fa-500px" },
        { icon: "fa-adn" },
        { icon: "fa-amazon" },
        { icon: "fa-android" },
        { icon: "fa-angellist" },
        { icon: "fa-apple" },
        { icon: "fa-bandcamp" },
        { icon: "fa-behance" },
        { icon: "fa-behance-square" },
        { icon: "fa-bitbucket" },
        { icon: "fa-bitbucket-square" },
        { icon: "fa-bitcoin" },
        { icon: "fa-black-tie" },
        { icon: "fa-bluetooth" },
        { icon: "fa-bluetooth-b" },
        { icon: "fa-btc" },
        { icon: "fa-buysellads" },
        { icon: "fa-cc-amex" },
        { icon: "fa-cc-diners-club" },
        { icon: "fa-cc-discover" },
        { icon: "fa-cc-jcb" },
        { icon: "fa-cc-mastercard" },
        { icon: "fa-cc-paypal" },
        { icon: "fa-cc-stripe" },
        { icon: "fa-cc-visa" },
        { icon: "fa-chrome" },
        { icon: "fa-codepen" },
        { icon: "fa-codiepie" },
        { icon: "fa-connectdevelop" },
        { icon: "fa-contao" },
        { icon: "fa-css3" },
        { icon: "fa-dashcube" },
        { icon: "fa-delicious" },
        { icon: "fa-deviantart" },
        { icon: "fa-digg" },
        { icon: "fa-dribbble" },
        { icon: "fa-dropbox" },
        { icon: "fa-drupal" },
        { icon: "fa-edge" },
        { icon: "fa-eercast" },
        { icon: "fa-empire" },
        { icon: "fa-envira" },
        { icon: "fa-etsy" },
        { icon: "fa-expeditedssl" },
        { icon: "fa-fa" },
        { icon: "fa-facebook" },
        { icon: "fa-facebook-f" },
        { icon: "fa-facebook-official" },
        { icon: "fa-facebook-square" },
        { icon: "fa-firefox" },
        { icon: "fa-first-order" },
        { icon: "fa-flickr" },
        { icon: "fa-font-awesome" },
        { icon: "fa-fonticons" },
        { icon: "fa-fort-awesome" },
        { icon: "fa-forumbee" },
        { icon: "fa-foursquare" },
        { icon: "fa-free-code-camp" },
        { icon: "fa-ge" },
        { icon: "fa-get-pocket" },
        { icon: "fa-gg" },
        { icon: "fa-gg-circle" },
        { icon: "fa-git" },
        { icon: "fa-git-square" },
        { icon: "fa-github" },
        { icon: "fa-github-alt" },
        { icon: "fa-github-square" },
        { icon: "fa-gitlab" },
        { icon: "fa-gittip" },
        { icon: "fa-glide" },
        { icon: "fa-glide-g" },
        { icon: "fa-google" },
        { icon: "fa-google-plus" },
        { icon: "fa-google-plus-circle" },
        { icon: "fa-google-plus-official" },
        { icon: "fa-google-plus-square" },
        { icon: "fa-google-wallet" },
        { icon: "fa-gratipay" },
        { icon: "fa-grav" },
        { icon: "fa-hacker-news" },
        { icon: "fa-houzz" },
        { icon: "fa-html5" },
        { icon: "fa-imdb" },
        { icon: "fa-instagram" },
        { icon: "fa-internet-explorer" },
        { icon: "fa-ioxhost" },
        { icon: "fa-joomla" },
        { icon: "fa-jsfiddle" },
        { icon: "fa-lastfm" },
        { icon: "fa-lastfm-square" },
        { icon: "fa-leanpub" },
        { icon: "fa-linkedin" },
        { icon: "fa-linkedin-square" },
        { icon: "fa-linode" },
        { icon: "fa-linux" },
        { icon: "fa-maxcdn" },
        { icon: "fa-meanpath" },
        { icon: "fa-medium" },
        { icon: "fa-meetup" },
        { icon: "fa-mixcloud" },
        { icon: "fa-modx" },
        { icon: "fa-odnoklassniki" },
        { icon: "fa-odnoklassniki-square" },
        { icon: "fa-opencart" },
        { icon: "fa-openid" },
        { icon: "fa-opera" },
        { icon: "fa-optin-monster" },
        { icon: "fa-pagelines" },
        { icon: "fa-paypal" },
        { icon: "fa-pied-piper" },
        { icon: "fa-pied-piper-alt" },
        { icon: "fa-pied-piper-pp" },
        { icon: "fa-pinterest" },
        { icon: "fa-pinterest-p" },
        { icon: "fa-pinterest-square" },
        { icon: "fa-product-hunt" },
        { icon: "fa-qq" },
        { icon: "fa-quora" },
        { icon: "fa-ra" },
        { icon: "fa-ravelry" },
        { icon: "fa-rebel" },
        { icon: "fa-reddit" },
        { icon: "fa-reddit-alien" },
        { icon: "fa-reddit-square" },
        { icon: "fa-renren" },
        { icon: "fa-resistance" },
        { icon: "fa-safari" },
        { icon: "fa-scribd" },
        { icon: "fa-sellsy" },
        { icon: "fa-share-alt" },
        { icon: "fa-share-alt-square" },
        { icon: "fa-shirtsinbulk" },
        { icon: "fa-simplybuilt" },
        { icon: "fa-skyatlas" },
        { icon: "fa-skype" },
        { icon: "fa-slack" },
        { icon: "fa-slideshare" },
        { icon: "fa-snapchat" },
        { icon: "fa-snapchat-ghost" },
        { icon: "fa-snapchat-square" },
        { icon: "fa-soundcloud" },
        { icon: "fa-spotify" },
        { icon: "fa-stack-exchange" },
        { icon: "fa-stack-overflow" },
        { icon: "fa-steam" },
        { icon: "fa-steam-square" },
        { icon: "fa-stumbleupon" },
        { icon: "fa-stumbleupon-circle" },
        { icon: "fa-superpowers" },
        { icon: "fa-telegram" },
        { icon: "fa-tencent-weibo" },
        { icon: "fa-themeisle" },
        { icon: "fa-trello" },
        { icon: "fa-tripadvisor" },
        { icon: "fa-tumblr" },
        { icon: "fa-tumblr-square" },
        { icon: "fa-twitch" },
        { icon: "fa-twitter" },
        { icon: "fa-twitter-square" },
        { icon: "fa-usb" },
        { icon: "fa-viacoin" },
        { icon: "fa-viadeo" },
        { icon: "fa-viadeo-square" },
        { icon: "fa-vimeo" },
        { icon: "fa-vimeo-square" },
        { icon: "fa-vine" },
        { icon: "fa-vk" },
        { icon: "fa-wechat" },
        { icon: "fa-weibo" },
        { icon: "fa-weixin" },
        { icon: "fa-whatsapp" },
        { icon: "fa-wikipedia-w" },
        { icon: "fa-windows" },
        { icon: "fa-wordpress" },
        { icon: "fa-wpbeginner" },
        { icon: "fa-wpexplorer" },
        { icon: "fa-wpforms" },
        { icon: "fa-xing" },
        { icon: "fa-xing-square" },
        { icon: "fa-y-combinator" },
        { icon: "fa-y-combinator-square" },
        { icon: "fa-yahoo" },
        { icon: "fa-yc" },
        { icon: "fa-yc-square" },
        { icon: "fa-yelp" },
        { icon: "fa-yoast" },
        { icon: "fa-youtube" },
        { icon: "fa-youtube-play" },
        { icon: "fa-youtube-square" },
      ],
      "Medical Icons": [
        { icon: "fa-ambulance" },
        { icon: "fa-h-square" },
        { icon: "fa-heart" },
        { icon: "fa-heart-o" },
        { icon: "fa-heartbeat" },
        { icon: "fa-hospital-o" },
        { icon: "fa-medkit" },
        { icon: "fa-plus-square" },
        { icon: "fa-stethoscope" },
        { icon: "fa-user-md" },
        { icon: "fa-wheelchair" },
        { icon: "fa-wheelchair-alt" },
      ],
    },
    //allIcons: [],
  }),
  mounted() {
    // this.tabs = ["all"].concat(this.tabs);
    // let all = [];
    // for (var item in this.icons) {
    //   all = all.concat(this.icons[item]);
    //   console.log(item);
    // }
    // this.allIcons = all;
  },
  computed: {
    // allIcons() {
    //   let all = [];
    //   for (var item in this.icons) {
    //     all = all.concat(this.icons[item]);
    //     console.log(item);
    //   }
    //   return all;
    // },
  },
  methods: {
    copyIcon(icon, event) {
      icon = ` <v-icon color="primary">${icon}</v-icon>`;
      clipboard(icon, event);
      console.log(icon);
    },
  },
};
</script>